### PR TITLE
Add Python type annotations to lab1 api, codec, and crypto

### PR DESCRIPTION
**Pull request by bkettle**
This PR adds type annotations to the api, codec, and crypto files of lab1. These annotations make it much easier to understand the code and determine how to use the functions it provides, at least for me. 

I tried my best to determine the types by reading through the code, but there may be a couple errors. I created this to be useful to myself on this lab and as a means of reading through the code, but it would be great to have these type annotations incorporated into future labs.

### CODE REVIEW

**Comment by derbear** [comment]
Thanks for the PR.

We thought about adding type annotations initially, but we decided against it as we weren't sure if students would be familiar with them. Perhaps we should revisit that choice if on balance, the annotations help with clarity/reduce type-related bugs (which are very easy to accidentally introduce in Python).

In either case, we probably won't merge this before lab 1 is due.

**Comment by bkettle** [comment]
Thanks for the response. Good to hear you thought about it, and indeed it might be confusing for some students, that's true. I personally find them super helpful especially in a codebase like this where most arguments are class instances, so I personally think they would be a great thing to introduce for future labs and future iterations of the course. I also feel like they're fairly simple/intuitive to learn even for people who haven't seen them. But I definitely understand the hesitation.

**Comment by bkettle** [comment]
Actually, after looking at the code for lab2, I think that there is a very sore need for type annotations in this codebase, or at the very least expected types in docstrings of all the functions (in client.py and public functions in other modules). Trying to understand verify_sign, for example, I have no idea what the datatype of pk should be until I jump through like 5 levels of definitions. I think it would save a lot of time and bring the focus of the labs onto implementation rather than requiring so much time to understand the structure of this codebase.

**Comment by derbear** [comment]
After discussing a bit with the other staff and getting some more feedback, we think the benefits of type annotations would outweigh the drawbacks. We'll add them in future iterations of the class, for sure, and possibly for future labs (lab4+) if we can easily do so (possibly only for new files we make).

Thanks again for the feedback!

**Pull request closed without merging**
